// 菜单 key → boxicons 类名（侧边栏图标）。
export const MENU_ICONS: Record<string, string> = {
  dashboard: 'bx-grid-alt',
  asset: 'bx-server',
  'database-asset': 'bx-data',
  'db-work-order': 'bx-task',
  credential: 'bx-key',
  snippet: 'bx-code-alt',
  storage: 'bx-hdd',
  website: 'bx-globe',
  certificate: 'bx-certification',
  gateway: 'bx-network-chart',
  'ssh-gateway': 'bx-terminal',
  'agent-gateway': 'bx-bot',
  'gateway-group': 'bx-collection',
  'online-session': 'bx-broadcast',
  'offline-session': 'bx-history',
  'exec-command-log': 'bx-terminal',
  'filesystem-log': 'bx-file',
  'access-log': 'bx-log-in',
  'access-log-stats': 'bx-bar-chart-alt-2',
  'login-log': 'bx-log-in-circle',
  'operation-log': 'bx-edit',
  'database-sql-log': 'bx-data',
  'scheduled-task': 'bx-time-five',
  tools: 'bx-wrench',
  monitoring: 'bx-line-chart',
  user: 'bx-user',
  'user-group': 'bx-group',
  department: 'bx-buildings',
  role: 'bx-id-card',
  'login-policy': 'bx-shield-quarter',
  'login-locked': 'bx-lock-alt',
  'oidc-client': 'bx-key',
  'command-filter': 'bx-filter-alt',
  strategy: 'bx-been-here',
  'authorised-asset': 'bx-server',
  'authorised-website': 'bx-globe',
  'authorised-database-asset': 'bx-data',
  setting: 'bx-cog',
  dev: 'bx-code-block',
}

export const iconOf = (key: string) => MENU_ICONS[key] ?? 'bx-circle'
